export { useIsAuthenticated } from "./useIsAuthenticated";
export type { UseIsAuthenticatedResult } from "./useIsAuthenticated";
export { useTouchDevice } from "./useTouchDevice";
export type { UseTouchDeviceResult } from "./useTouchDevice";
export { useDeviceCapabilities } from "./useDeviceCapabilities";
export type { DeviceCapabilities, DeviceTier } from "./useDeviceCapabilities";
export { useFPSMonitor } from "./useFPSMonitor";
export type { FPSMonitorConfig, FPSMonitorResult } from "./useFPSMonitor";
export { useEffectsPreference } from "./useEffectsPreference";
export type { EffectsPreferenceResult } from "./useEffectsPreference";
